# Generated by Django 4.2.1 on 2023-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='status',
            field=models.CharField(default='Awaiting', max_length=15),
        ),
    ]
